### ISSUE TITLE
本地 clash 订阅 ss2022 协议导出 V2Ray 解析错误

### ISSUE THREAD

**Issue by soffio** [sub-store-org/Sub-Store#404]
```
proxies:
- name: "test"
  type: ss
  server: 1.1.1.1
  port: 1234
  cipher: 2022-blake3-aes-128-gcm
  password: sRV5GHyHjC4p+T4F6ly3IQ==
```
使用上面的本地订阅，导出 V2Ray 解析错误，解码后是
`ss://2022-blake3-aes-128-gcm:sRV5GHyHjC4p%2BT4F6ly3IQ%3D%3D@1.1.1.1:1234#test`

cipher改成 `aes-256-gcm` 可正常解析，导出 V2Ray 解码后是
`ss://YWVzLTI1Ni1nY206c1JWNUdIeUhqQzRwK1Q0RjZseTNJUT09@1.1.1.1:1234#test`
