### ISSUE TITLE
请求增加分享类型

### ISSUE THREAD

**Issue by ma3252788** [sub-store-org/Sub-Store#432]
感谢大佬。

目前的分享形式貌似只有一种默认的形式，比如`dm1lc3M6Ly9leUoySWpvaU1pSXNJbkJ6SWpvaWFVdDFkWFh3bjRldjhKK0h0U0RsaFkzb3RMa3Q1cGVsNXB5c01TMVdaWEl1TmlJc0ltRmtaQ0k2SW01dGFYUTRMV2N3TVM1cWNEQXhMVEE1T0RZdGRtMHdMbVZ1ZEhKNUxtWnlNRE13TjJFdVlYSjBJaXdpY0c5eWRDSTZNakUxT0RFc0ltbGtJam9pWXpobVpEWTVNbUV0T0RJeE5DMHpOakU0TFRsbE56RXRNVEF6TWpSaU1t==`这种，如果单独在clash中用是没问题的，但是如果作为订阅链接放到配置文件中就出错了，比如：

```
#SUBSCRIBED https://sub.201.xyz/share/col/free2?token=E7VRU2dKi
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: Rule
log-level: info
ipv6: false
hosts: null
dns:
    enable: true
    ipv6: false
    listen: '0.0.0.0:1053'
    use-hosts: true
    default-nameserver: [119.28.28.28, 119.29.29.29, 223.5.5.5, 223.6.6.6]
    nameserver: [119.28.28.28, 119.29.29.29, 223.5.5.5, 223.6.6.6]
    fallback: ['https://dns.pub/dns-query', 'https://doh.pub/dns-query', 'https://doh.apad.pro/dns-query', 'https://dns.alidns.com/dns-query', 'tls://dns.pub:853', 'tls://dot.pub:853', 'tls://dns.alidns.com:853', 119.28.28.28, 119.29.29.29, 223.5.5.5, 223.6.6.6]
    fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 233.252.0.0/24, 240.0.0.0/4, 255.255.255.255/32, '::/128', '::1/128', 'fc00::/7', 'fe80::/10', 'ff00::/8'] }
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter: ['*.lan', '*.localdomain', '*.example', '*.invalid', '*.localhost', '*.test', '*.local', '*.home.arpa', 'time.*.com', 'time.*.gov', 'time.*.edu.cn', 'time.*.apple.com', 'time1.*.com', 'time2.*.com', 'time3.*.com', 'time4.*.com', 'time5.*.com', 'time6.*.com', 'time7.*.com', 'ntp.*.com', 'ntp1.*.com', 'ntp2.*.com', 'ntp3.*.com', 'ntp4.*.com', 'ntp5.*.com', 'ntp6.*.com', 'ntp7.*.com', '*.time.edu.cn', '*.ntp.org.cn', +.pool.ntp.org, time1.cloud.tencent.com, 'stun.*.*', 'stun.*.*.*', swscan.apple.com, mesu.apple.com, music.163.com, '*.music.163.com', '*.126.net', musicapi.taihe.com, music.taihe.com, songsearch.kugou.com, trackercdn.kugou.com, '*.kuwo.cn', api-jooxtt.sanook.com, api.joox.com, y.qq.com, '*.y.qq.com', streamoc.music.tc.qq.com, mobileoc.music.tc.qq.com, isure.stream.qqmusic.qq.com, dl.stream.qqmusic.qq.com, aqqmusic.tc.qq.com, amobile.music.tc.qq.com, localhost.ptlogin2.qq.com, '*.msftconnecttest.com', '*.msftncsi.com', '*.xiami.com', '*.music.migu.cn', music.migu.cn, +.wotgame.cn, +.wggames.cn, +.wowsgame.cn, +.wargaming.net, '*.*.*.srv.nintendo.net', '*.*.stun.playstation.net', 'xbox.*.*.microsoft.com', '*.*.xboxlive.com', '*.ipv6.microsoft.com', 'teredo.*.*.*', 'teredo.*.*', speedtest.cros.wr.pvp.net, +.jjvip8.com, www.douyu.com, activityapi.huya.com, activityapi.huya.com.w.cdngslb.com, www.bilibili.com, api.bilibili.com, a.w.bilicdn1.com]
external-controller: '127.0.0.1:9090'
clash-for-android:
    append-system-dns: false
profile:
    tracing: true
proxy-providers:
    Subscribe: 
        type: http  
        interval: 600
        url: https://sub.201.xyz/share/col/free2?token=E7VRU2dKi
xxxxxxx
```

这里我把https://sub.201.xyz/share/col/free2?token=E7VRU2dKi作为订阅的话，如果在Stash中就没问题，但是放到clash中，就会报错：

<img width="552" alt="Image" src="https://github.com/user-attachments/assets/ba95dd9a-dd58-4b39-8c26-dedaae6a0d58" />

但是我测试了?target=Clash这种形式，就没问题~~

可是在对外分享的时候，如果在分享链接后面加了?target=Clash，就直接报错了~~

所以，能否在分享的时候也增加分享类型的选择呢？

**我测试了文件同步gist的方式，可是这种方式太不稳了，经常无法访问github，有时候地址前面加了代理也不行。**

再次感谢大佬。
