### ISSUE TITLE
vless-reality-vision节点转换sing-box节点格式后，multiplex配置部分丢失

### ISSUE THREAD

**Issue by KuGouGo** [sub-store-org/Sub-Store#443]
这个是在sub-store本地添加的vless-reality-vision节点yaml配置
```
proxies:
  - name: 🇺🇸US reality-vision
    type: vless
    server: 
    port: 
    uuid: 
    tls: true
    servername: xzd.dns-dynamic.net
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: 
      short-id: 
    smux:
      enabled: true
      protocol: h2mux
      max-connections: 8
      min-streams: 16
      statistic: true
      only-tcp: false
      padding: true
      brutal-opts:
        enabled: true
        up: 1000
        down: 1000
```
这个是预览sing-box生成后的配置
```
{
  "outbounds": [
    {
      "tag": "🇺🇸US reality-vision",
      "type": "vless",
      "server": "",
      "server_port": ,
      "uuid": "",
      "tls": {
        "enabled": true,
        "server_name": "xzd.dns-dynamic.net",
        "insecure": false,
        "reality": {
          "enabled": true,
          "public_key": "",
          "short_id": ""
        },
        "utls": {
          "enabled": true,
          "fingerprint": "chrome"
        }
      },
      "flow": "xtls-rprx-vision",
      "multiplex": {
        "enabled": true,
        "protocol": "h2mux",
        "max_connections": 8,
        "min_streams": 16,
        "padding": true
      }
    }
  ]
}
```
